module.exports = {
    loggedIn: false,
    token: null,
    id: null,
    role: null,
    name: null,
    customerName: null,
    driverStatus: null,
    hotelLat: null,
    hotelLng:null,
    placeId:null,
    orderCode: null,
    orderStatus:null,
    startLat:null,
    startLng:null,
    endLat:null,
    endLng:null,
    phone: null,
    orderId:null,
    address:null,
    interVal1:null,
    interVal2:null,
    interVal3:null,
    interVal4:null,
    interVal5:null,
    render:false,
};